"""account owned recipe imports

Revision ID: 20260908_11
Revises: 20260908_10
Create Date: 2026-09-08 18:17:49.240399
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260908_11"
down_revision: str | None = "20260908_10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imported_recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("nutrition_choice", sa.String(length=16), nullable=False),
        sa.Column("library_saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "user_id"),
    )
    op.create_index(
        op.f("ix_imported_recipes_user_id"), "imported_recipes", ["user_id"], unique=False
    )
    op.create_table(
        "recipe_import_commands",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "request_id"),
    )
    op.create_table(
        "imported_recipe_ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id", "user_id"],
            ["imported_recipes.id", "imported_recipes.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "position"),
    )
    op.create_index(
        op.f("ix_imported_recipe_ingredients_recipe_id"),
        "imported_recipe_ingredients",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "imported_recipe_nutrition",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id", "user_id"],
            ["imported_recipes.id", "imported_recipes.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", "kind"),
    )
    op.create_table(
        "imported_recipe_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id", "user_id"],
            ["imported_recipes.id", "imported_recipes.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "position"),
    )
    op.create_index(
        op.f("ix_imported_recipe_steps_recipe_id"),
        "imported_recipe_steps",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "recipe_import_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["imported_recipes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_import_jobs_user_id"), "recipe_import_jobs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_recipe_jobs_due",
        "recipe_import_jobs",
        ["state", "next_attempt_at", "lease_until"],
        unique=False,
    )
    op.create_table(
        "recipe_import_sources",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["recipe_import_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM imported_recipes")):
        raise RuntimeError("Export imported recipes before removing their storage.")
    op.drop_table("recipe_import_sources")
    op.drop_index("ix_recipe_jobs_due", table_name="recipe_import_jobs")
    op.drop_index(op.f("ix_recipe_import_jobs_user_id"), table_name="recipe_import_jobs")
    op.drop_table("recipe_import_jobs")
    op.drop_index(op.f("ix_imported_recipe_steps_recipe_id"), table_name="imported_recipe_steps")
    op.drop_table("imported_recipe_steps")
    op.drop_table("imported_recipe_nutrition")
    op.drop_index(
        op.f("ix_imported_recipe_ingredients_recipe_id"), table_name="imported_recipe_ingredients"
    )
    op.drop_table("imported_recipe_ingredients")
    op.drop_table("recipe_import_commands")
    op.drop_index(op.f("ix_imported_recipes_user_id"), table_name="imported_recipes")
    op.drop_table("imported_recipes")
    # ### end Alembic commands ###
