"""guided_cooking_sessions

Revision ID: e449764316ff
Revises: 20260908_11
Create Date: 2026-09-08 21:04:40.602832
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e449764316ff"
down_revision: str | None = "20260908_11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cooking_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('in_progress','awaiting_confirmation','completed','abandoned')"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cooking_sessions_user_id"), "cooking_sessions", ["user_id"], unique=False
    )
    op.create_index(
        "one_unfinished_cooking_session",
        "cooking_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('in_progress','awaiting_confirmation')"),
        sqlite_where=sa.text("status IN ('in_progress','awaiting_confirmation')"),
    )
    op.create_table(
        "cooking_commands",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["cooking_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "request_id"),
    )
    op.create_table(
        "cooking_consumptions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("lots", sa.JSON(), nullable=False),
        sa.Column("uses", sa.JSON(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["cooking_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_cooking_consumptions_user_id"), "cooking_consumptions", ["user_id"], unique=False
    )


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM cooking_sessions")):
        raise RuntimeError("Export cooking sessions before removing their storage.")
    op.drop_table("cooking_commands")
    op.drop_table("cooking_consumptions")
    op.drop_table("cooking_sessions")
